server.port=8084

spring.kafka.bootstrap-servers=${KAFKA_SERVICE_URL:kafka-877fe57-ordernest.i.aivencloud.com:14046}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SSL}
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=${KAFKA_TRUSTSTORE_PATH:/app/ssl/ca.pem}
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=${KAFKA_KEYSTORE_PATH:/app/ssl/client.keystore.p12}
spring.kafka.properties.ssl.keystore.password=${KAFKA_KEYSTORE_PASSWORD:changeit}

app.kafka.topic.shipment-events=${SHIPMENT_EVENTS_TOPIC:shipment.events}
app.jwt.secret=${JWT_SECRET:change-me-in-prod-change-me-in-prod-change-me}
